# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20171213_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='regdate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
