# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sort',
            field=models.CharField(default='None', max_length=30, verbose_name='\u7c7b\u522b'),
        ),
    ]
