# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0004_auto_20171213_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default='False', verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
