# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0006_auto_20171214_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
