# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0003_auto_20171213_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adddate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4'),
        ),
    ]
