# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0009_auto_20171216_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='goodname',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
