# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0011_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goodname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
