# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('item_num', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u8d27\u53f7')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d')),
                ('imge', models.ImageField(upload_to='good_img', verbose_name='\u56fe\u7247')),
                ('sales', models.IntegerField(verbose_name='\u9500\u91cf')),
                ('stock', models.IntegerField(verbose_name='\u5e93\u5b58')),
            ],
        ),
    ]
